// Package v1 GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package v1

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "s.vie4m@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign-in to share .",
                "parameters": [
                    {
                        "description": "Sign-in object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SignIn"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "signin information",
                        "schema": {
                            "$ref": "#/definitions/v1.SignInResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign-out from share.",
                "responses": {
                    "200": {
                        "description": "Sign-out success",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign-up to share.",
                "parameters": [
                    {
                        "description": "Sign-up object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.SignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "response information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/position": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "position"
                ],
                "summary": "Update position to share",
                "parameters": [
                    {
                        "description": "Update current position object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateCurrentPosition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Position information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/position/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "position"
                ],
                "summary": "Search current position to share",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude for location-based search",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude for location-based search",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Radius for location-based search in meters",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "position information",
                        "schema": {
                            "$ref": "#/definitions/v1.SearchCurrentPositionResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/session": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Update session to share",
                "parameters": [
                    {
                        "description": "Update session object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateSession"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Create session to share",
                "parameters": [
                    {
                        "description": "Create session object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.CreateSession"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session information",
                        "schema": {
                            "$ref": "#/definitions/v1.CreateSessionResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/session/finish": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Finish session position to share",
                "parameters": [
                    {
                        "description": "Finish session object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.FinishSession"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/session/position": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Update session position to share",
                "parameters": [
                    {
                        "description": "Update session position object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/v1.UpdateSessionPosition"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/session/search/{sessionID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Search session to share",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude for location-based search",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude for location-based search",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Radius for location-based search in meters",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/session/{sessionID}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "session"
                ],
                "summary": "Delete session to share",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Session ID to be deleted",
                        "name": "sessionID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "session information",
                        "schema": {
                            "$ref": "#/definitions/v1.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.CreateSession": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "optional",
                    "type": "string"
                },
                "is_finished": {
                    "type": "boolean"
                },
                "is_shared": {
                    "type": "boolean"
                },
                "position": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Point"
                    }
                },
                "title": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "v1.CreateSessionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.Session"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.FinishSession": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "v1.Point": {
            "type": "object",
            "properties": {
                "t": {
                    "description": "required timestamp",
                    "type": "integer"
                },
                "x": {
                    "description": "optional latitude",
                    "type": "number"
                },
                "y": {
                    "description": "optional longitude",
                    "type": "number"
                },
                "z": {
                    "description": "optional elevation (if not provided, will be set to 0)",
                    "type": "number"
                }
            }
        },
        "v1.Position": {
            "type": "object",
            "properties": {
                "position": {
                    "$ref": "#/definitions/v1.Point"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.SearchCurrentPositionResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Position"
                    }
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.Session": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "delete_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_finished": {
                    "type": "boolean"
                },
                "is_shared": {
                    "type": "boolean"
                },
                "position": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Point"
                    }
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "v1.SignIn": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.SignInResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {
                    "$ref": "#/definitions/v1.Token"
                },
                "msg": {
                    "type": "string"
                }
            }
        },
        "v1.SignUp": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "v1.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "v1.UpdateCurrentPosition": {
            "type": "object",
            "properties": {
                "position": {
                    "description": "optional",
                    "$ref": "#/definitions/v1.Point"
                }
            }
        },
        "v1.UpdateSession": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "optional",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_shared": {
                    "type": "boolean"
                },
                "title": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "v1.UpdateSessionPosition": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "position": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v1.Point"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "share API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
