// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time"},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: "good trip"},
		{Name: "title", Type: field.TypeString, Default: "trip c25b67a9-ef50-4725-bac4-3a6c6ad1b9e4"},
		{Name: "position", Type: field.TypeJSON, Nullable: true},
		{Name: "is_finished", Type: field.TypeBool, Default: false},
		{Name: "is_shared", Type: field.TypeBool, Default: false},
		{Name: "user_id", Type: field.TypeUUID, Comment: "User's UUID"},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_users",
				Columns:    []*schema.Column{SessionsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "session_user_id",
				Unique:  false,
				Columns: []*schema.Column{SessionsColumns[9]},
			},
		},
	}
	// TokensColumns holds the columns for the "tokens" table.
	TokensColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time"},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "token", Type: field.TypeString, Comment: "Token string"},
		{Name: "user_id", Type: field.TypeUUID, Comment: "User's UUID"},
	}
	// TokensTable holds the schema information for the "tokens" table.
	TokensTable = &schema.Table{
		Name:       "tokens",
		Columns:    TokensColumns,
		PrimaryKey: []*schema.Column{TokensColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tokens_users_users",
				Columns:    []*schema.Column{TokensColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "token_user_id",
				Unique:  false,
				Columns: []*schema.Column{TokensColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "Update Time"},
		{Name: "delete_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_name", Type: field.TypeString, Size: 100},
		{Name: "email", Type: field.TypeString, Size: 100},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true},
		{Name: "password_hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SessionsTable,
		TokensTable,
		UsersTable,
	}
)

func init() {
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	TokensTable.ForeignKeys[0].RefTable = UsersTable
}
